# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170514_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(default='blah', upload_to='blog/static/img/'),
        ),
    ]
