# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(default='../static/img/no-img.jpg', upload_to='../static/img/'),
        ),
    ]
