# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170514_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(default='/Users/ChristopherMelville/Sites/castawayyourworries/blog/mediaimg/monkey.jpg', upload_to='blog/media/img/'),
        ),
    ]
