# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170514_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(db_index=True, max_length=255)),
                ('about_text', models.TextField()),
                ('about_image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('mailing_list_text', models.TextField()),
            ],
        ),
    ]
